name: Docker Image CI with Minikube Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . -f Dockerfile -t dileep10/my-image-name:latest

    - name: Push the Docker image to Docker Hub (Optional)
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "dileep10" --password-stdin
        docker push dileep10/my-image-name:latest  # Optional step

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v4

    - name: Verify working directory (Optional)
      run: pwd

    - name: Check for deployment.yaml
      run: ls deployment.yaml

    - name: Use Minikube kubectl context (Optional)
      uses: Azure/login@v1  # This step can be replaced with a custom script
        with:
          clientSecret: ${{ secrets.AZURE_AUTH_TOKEN }}  # Replace with your actual secret
          defaults: kubectl-context=minikube  # Sets the context to minikube

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml --validate=false

    - name: Get Service NodePort (Optional)
      run: |
        kubectl get service -o jsonpath="{.items[0].spec.ports[0].nodePort}"
        id: get-nodeport

    - name: Test Application (Optional)
      run: |
        curl http://localhost:${{ steps.get-nodeport.outputs.get_nodeport }}  # Access service (if NodePort retrieved)
