deploy:
  runs-on: ubuntu-latest
  needs: [build]

  steps:
  - uses: actions/checkout@v4

  - name: Start Minikube (using docker driver)
    run: minikube start  # No need for --driver option

  - name: Verify Minikube Status (Optional)
    run: minikube status  # Check if Minikube is already running

  - name: Install Kubectl (Optional, if not already installed)
    uses: azure/setup-kubectl@v3
    with:
      version: 'latest'  # Adjust version if needed

  - name: Use Minikube kubectl context
    run: kubectl config use-context minikube

  - name: Verify working directory (Optional)
    run: pwd

  - name: Check for deployment.yaml
    run: ls deployment.yaml

  - name: Deploy to Minikube
    run: |
      kubectl apply -f deployment.yaml --validate=false

  - name: Get Service NodePort (Optional)
    id: get-nodeport
    run: |
      kubectl get service -o jsonpath="{.items[0].spec.ports[0].nodePort}"

  - name: Test Application (Optional)
    run: |
      curl http://localhost:${{ steps.get-nodeport.outputs.nodePort }}  # Access service (if NodePort retrieved)
