name: Docker Image CI with Minikube Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build the Docker image
      run: |
        docker build . -f Dockerfile -t dileep10/my-image-name:latest

    - name: Push the Docker image to Docker Hub (Optional)
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push dileep10/my-image-name:latest  # Optional step

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v4

    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Install Conntrack
      run: sudo apt-get install -y conntrack

    - name: Install Crictl
      run: |
        VERSION="v1.24.1"
        curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/${VERSION}/crictl-${VERSION}-linux-amd64.tar.gz
        sudo tar zxvf crictl-${VERSION}-linux-amd64.tar.gz -C /usr/local/bin
        rm -f crictl-${VERSION}-linux-amd64.tar.gz

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        sudo minikube start --driver=none

    - name: Verify Minikube Status
      run: minikube status

    - name: Use Minikube kubectl context
      run: |
        kubectl config use-context minikube

    - name: Verify working directory (Optional)
      run: pwd

    - name: Check for deployment.yaml
      run: ls deployment.yaml

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml --validate=false

    - name: Get Service NodePort (Optional)
      id: get-nodeport
      run: |
        kubectl get service -o jsonpath="{.items[0].spec.ports[0].nodePort}"

    - name: Test Application (Optional)
      run: |
        curl http://localhost:${{ steps.get-nodeport.outputs.nodePort }}  # Access service (if NodePort retrieved)
